language: python
fast_finish: true

python:
  - 3.6
  - 2.7

os:
  - linux

group: travis_latest

git:
  depth: 3


install: python -m pip install -e .[tests]

script: coverage run tests/test.py -v

after_success: coveralls
