language: python
python:
#  - "3.4"
  - "2.7"
before_install: 
 sudo apt-get install -qq python-numpy python-scipy
install: pip install  -q --allow-all-external  -r requirements.txt

script:  python maxent.py
